# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e8f5f0cc8dcb990f6fa2dc0b57f60abec7260aff911cc7baea518b6b09debf930d20a9aa9d71f4394d25a97a7d33f02b2745fc98671d1c2dcb8911e5b675303

test:
  secret_key_base: 79351e622684366cf73837541b7451bbb82feed1260fb71402f625590f1c81957dc5da5e190463a1ffc42e59645f3b4a593ef8f424b384e53c9c4b694188bcb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
